# Generated by Django 2.2.2 on 2019-06-23 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tagging.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mydogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('dogpic', models.ImageField(default='photos/no_image.png', upload_to='photos/%Y/%m/%d')),
                ('birth', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('species', models.CharField(max_length=50)),
                ('registernumber', models.IntegerField()),
                ('gender', models.CharField(max_length=15)),
                ('neutral', models.BooleanField()),
                ('dhppl', models.DateField(blank=True, null=True)),
                ('corona', models.DateField(blank=True, null=True)),
                ('kennel', models.DateField(blank=True, null=True)),
                ('rabies', models.DateField(blank=True, null=True)),
                ('heartworm', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('walkcount', models.IntegerField()),
                ('walktime', models.TimeField(blank=True, null=True)),
                ('foodamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('snackcount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('statustrace', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tag', tagging.fields.TagField(blank=True, max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_daily', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
