# Generated by Django 2.2.2 on 2019-07-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='statustrace',
            field=models.TextField(blank=True, null=True),
        ),
    ]
