# Generated by Django 2.2.2 on 2019-06-16 16:59

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190617_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='KRW', max_digits=10),
        ),
    ]
