# Generated by Django 2.2.2 on 2019-07-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190617_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desimage',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/description'),
        ),
    ]
