# Generated by Django 2.2.2 on 2019-07-10 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_orderuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
