# Generated by Django 2.2.2 on 2019-07-10 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190710_1517'),
    ]

