# Generated by Django 2.2.2 on 2019-07-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20190711_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
