# Generated by Django 2.2.2 on 2019-07-10 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20190711_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderuser',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
